### login as admin
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
	"username": "akbarjondev007@gmail.com",
	"password": "root123"
}

### create teacher as admin
POST http://localhost:8080/api/v1/teacher
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJha2JhcmpvbmRldjAwN0BnbWFpbC5jb20iLCJ1c2VySWQiOiIyMDc3NTJjMy02Y2E0LTQzZTktYTlhZS1mOWFkM2E5ZjM4M2EiLCJhdXRob3JpdGllcyI6W3siYXV0aG9yaXR5IjoiUk9MRV9ST0xFX0FETUlOIn1dLCJpYXQiOjE3NTE4OTQ5NjMsImV4cCI6MTc1MTg5ODU2M30.1BZuV_P03jnnEufxU-iD-3ZhM2L9dcWA3obqo6vDEvzVqOZ6ChmwHj_I8ZzgcYsKmF2r652bmflBUoE9u0X7ug
Content-Type: application/json

{
	"username": "teacher@gmail.com",
	"password": "root123",
	"firstName": "teacherjon",
	"lastName": "teacherov",
	"phoneNumber": "+998945060749",
	"specialization": "programming",
	"qualification": "bachelor",
	"hireDate": "2024-01-15"
}

### get all teachers in page as admin
GET http://localhost:8080/api/v1/teacher
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJha2JhcmpvbmRldjAwN0BnbWFpbC5jb20iLCJ1c2VySWQiOiIyMDc3NTJjMy02Y2E0LTQzZTktYTlhZS1mOWFkM2E5ZjM4M2EiLCJhdXRob3JpdGllcyI6W3siYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiaWF0IjoxNzUxOTEyNzAwLCJleHAiOjE3NTE5MTYzMDB9.36Py0KrcETadGKdJg8CzfXnc76vC_tUiWz55TBJ_43t785fQI4AwjVEdbmX7W6qSmlHN9pkNT6dzyo58E5L3SQ

### get a teacher by id as admin
GET http://localhost:8080/api/v1/teacher/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJha2JhcmpvbmRldjAwN0BnbWFpbC5jb20iLCJ1c2VySWQiOiIyMDc3NTJjMy02Y2E0LTQzZTktYTlhZS1mOWFkM2E5ZjM4M2EiLCJhdXRob3JpdGllcyI6W3siYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiaWF0IjoxNzUxOTEyNzAwLCJleHAiOjE3NTE5MTYzMDB9.36Py0KrcETadGKdJg8CzfXnc76vC_tUiWz55TBJ_43t785fQI4AwjVEdbmX7W6qSmlHN9pkNT6dzyo58E5L3SQ

### delete (SOFT) a teacher by id as admin
DELETE http://localhost:8080/api/v1/teacher/1?deleteType=SOFT
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJha2JhcmpvbmRldjAwN0BnbWFpbC5jb20iLCJ1c2VySWQiOiIyMDc3NTJjMy02Y2E0LTQzZTktYTlhZS1mOWFkM2E5ZjM4M2EiLCJhdXRob3JpdGllcyI6W3siYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiaWF0IjoxNzUxOTEyNzAwLCJleHAiOjE3NTE5MTYzMDB9.36Py0KrcETadGKdJg8CzfXnc76vC_tUiWz55TBJ_43t785fQI4AwjVEdbmX7W6qSmlHN9pkNT6dzyo58E5L3SQ

### delete (HARD) a teacher by id as admin
DELETE http://localhost:8080/api/v1/teacher/1?deleteType=HARD
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJha2JhcmpvbmRldjAwN0BnbWFpbC5jb20iLCJ1c2VySWQiOiIyMDc3NTJjMy02Y2E0LTQzZTktYTlhZS1mOWFkM2E5ZjM4M2EiLCJhdXRob3JpdGllcyI6W3siYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9XSwiaWF0IjoxNzUxOTEyNzAwLCJleHAiOjE3NTE5MTYzMDB9.36Py0KrcETadGKdJg8CzfXnc76vC_tUiWz55TBJ_43t785fQI4AwjVEdbmX7W6qSmlHN9pkNT6dzyo58E5L3SQ
